server:
  port: 8089

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  